from enum import Enum

class DataType(Enum):
    int8 = ...
    uint8 = ...
    short = ...
    int16 = ...  # alias for dtype short
    int = ...
    int32 = ...  # alias for dtype int
    long = ...
    int64 = ...  # alias for dtype long
    half = ...
    float16 = ...  # alias for dtype half
    float = ...
    float32 = ...  # alias for dtype float
    double = ...
    float64 = ...  # alias for dtype double
