from typing import Sequence

from ..memory.memory import MemoryPtr
from .specs import ColumnSpec, TableSpec

class TrajectoryTable:
    def __init__(self, spec: TableSpec, key: int, create: bool) -> TrajectoryTable: ...
    @property
    def ncolumns(self) -> int: ...
    def get_table_spec(self) -> TableSpec: ...
    def get_column_spec(self) -> Sequence[ColumnSpec]: ...
    def get_address(self) -> MemoryPtr: ...
    def connect(self) -> int: ...
